"""renames some columns in Planet model

Revision ID: 7f08ca30df24
Revises: 4d6241440afd
Create Date: 2021-05-04 20:01:50.273047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f08ca30df24'
down_revision = '4d6241440afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('day_length_in_hours', sa.Float(), nullable=True))
    op.add_column('planet', sa.Column('size_in_miles', sa.Float(), nullable=True))
    op.add_column('planet', sa.Column('year_length_in_earth_days', sa.Float(), nullable=True))
    op.drop_column('planet', 'size')
    op.drop_column('planet', 'year_length')
    op.drop_column('planet', 'day_length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('day_length', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('planet', sa.Column('year_length', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('planet', sa.Column('size', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('planet', 'year_length_in_earth_days')
    op.drop_column('planet', 'size_in_miles')
    op.drop_column('planet', 'day_length_in_hours')
    # ### end Alembic commands ###
