"""renames size_in_miles column to radius_in_miles

Revision ID: e61ab5e9f7d7
Revises: 7f08ca30df24
Create Date: 2021-05-04 20:11:41.268018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e61ab5e9f7d7'
down_revision = '7f08ca30df24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('radius_in_miles', sa.Float(), nullable=True))
    op.drop_column('planet', 'size_in_miles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('size_in_miles', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('planet', 'radius_in_miles')
    # ### end Alembic commands ###
